version: '2'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: 10.250.195.52
      MYSQL_USERNAME: gowebapp
      MYSQL_ROOT_PASSWORD: go_hack_me_now
      MYSQL_PASS: go_hack_me_now